<?php

namespace Database\Factories;

use App\Models\Product;
use App\Models\Market;
use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

class ProductFactory extends Factory
{
    protected $model = Product::class;

    public function definition(): array
    {
        $categories = [
            'Office Supplies',
            'Industrial Components',
            'IT Hardware',
            'Packaging',
            'Maintenance',
            'Safety Equipment',
            'Furniture & Fixtures',
            'Electrical Supplies',
            'Laboratory Supplies',
            'Catering & Kitchen',
            'Printing & Stationery',
            'Tools & Equipment',
            'Automotive Supplies',
            'Medical Supplies',
            'Textiles & Uniforms',
            'Gardening & Grounds',
            'Security & Surveillance',
            'HVAC & Ventilation',
            'Janitorial Equipment',
            'Signage & Display',
        ];

        $category = $this->faker->randomElement($categories);
        $categoryId = Category::firstOrCreate(['name' => $category])->id;

        $baseName = match ($category) {
            'Office Supplies' => $this->faker->randomElement([
                'A4 Copy Paper 80gsm Ream (500 sheets)',
                'A3 Copy Paper 100gsm Premium White',
                'Ballpoint Pens Blue Medium Point (Pack of 50)',
                'Roller Gel Pens Black 0.7mm (Box of 12)',
                'Office Desk Chair Ergonomic Mesh Back',
                'Executive Leather Chair with Lumbar Support',
                'Whiteboard Markers Assorted Colors (Pack of 4)',
                'Permanent Markers Black Chisel Tip (Pack of 12)',
                'Stapler Heavy Duty 100 Sheet Capacity',
                'Staples 26/6 Galvanized (Box of 5000)',
                'Lever Arch File A4 75mm Spine Assorted',
                'Ring Binder A4 2-Ring 25mm Capacity',
                'Sticky Notes 76x76mm Yellow (Pack of 12)',
                'Page Markers Assorted Neon 5 Colors',
                'Calculator Desktop 12 Digit Solar Powered',
                'Paper Clips 33mm Steel (Box of 1000)',
                'Rubber Bands Assorted Sizes 500g Box',
                'Correction Fluid White 20ml Bottle',
                'Desk Organizer 6 Compartment Mesh Metal',
                'Document Tray 3-Tier Metal Black',
                'Printer Labels A4 21 per sheet (100 sheets)',
                'Envelopes DL 110x220mm White Self Seal (500)',
                'Hanging File Folders A4 Green (Pack of 25)',
                'Magazine File Holder Cardboard Black',
                'Desktop Hole Punch 2-Hole 30 Sheet',
            ]),
            'Industrial Components' => $this->faker->randomElement([
                'M8x20mm Hex Bolt Stainless Steel A2 Grade',
                'M10x30mm Socket Cap Screw Grade 8.8',
                'M6 Nylon Insert Lock Nut Zinc Plated (100)',
                'M12 Flat Washer Stainless Steel (Pack of 50)',
                'Hydraulic Hose 1/2" 4000PSI Working Pressure',
                'Hydraulic Hose 3/4" 2-Wire Braid 350 Bar',
                'Pneumatic Fitting 1/4" Push-to-Connect',
                'Quick Release Coupling 1/2" BSP Male',
                'Industrial Safety Gloves Nitrile Coated Size 9',
                'Cut Resistant Gloves Level 5 Kevlar Palm',
                'PPE Safety Helmet EN397 Adjustable White',
                'Hard Hat Vented with Ratchet Suspension Yellow',
                'Ball Bearing 6206 2RS Deep Groove',
                'Roller Chain 08B-1 Simplex 1/2" Pitch',
                'V-Belt Classical A Section 13x8mm',
                'Timing Belt HTD 5M 15mm Width 500mm Length',
                'Grease Nipple 1/4" BSP Straight (Pack of 10)',
                'Oil Seal 30x47x7mm Nitrile Rubber',
                'Wire Rope 6mm Diameter Galvanized 6x19',
                'Shackle Bow Type 1 Tonne Galvanized',
                'Eye Bolt M12 Forged Steel Rated Load 0.5T',
                'Spring Washer M10 High Tensile (100)',
                'Circlip Internal 25mm Dia Carbon Steel',
                'Dowel Pin 6x30mm Hardened Ground',
                'Cable Tie 200x4.8mm Natural Nylon (Pack of 100)',
            ]),
            'IT Hardware' => $this->faker->randomElement([
                '24" LED Monitor Full HD 1920x1080 VGA HDMI',
                '27" IPS Monitor 2560x1440 QHD USB-C',
                '32" Curved Monitor 4K UHD 3840x2160 144Hz',
                'Business Laptop 16GB RAM 512GB SSD i5 Gen12',
                'Professional Laptop 32GB RAM 1TB SSD i7 Gen13',
                'Ultrabook 14" 8GB RAM 256GB SSD Lightweight',
                'Network Switch 24 Port Gigabit Managed PoE+',
                'Network Switch 48 Port Gigabit Stackable',
                'Network Switch 8 Port Gigabit Unmanaged Desktop',
                'External SSD 1TB USB-C 3.2 Gen2 550MB/s',
                'External HDD 4TB USB 3.0 Portable Backup',
                'USB Flash Drive 128GB USB 3.1 Metal Casing',
                'Wireless Mouse Optical 2.4GHz 1600DPI Ergonomic',
                'Mechanical Keyboard RGB Backlit Cherry MX Brown',
                'Webcam 1080p Full HD Auto Focus Built-in Mic',
                'USB-C Docking Station Triple Display 100W PD',
                'KVM Switch 4 Port HDMI USB 3.0 4K@60Hz',
                'Ethernet Cable Cat6 3m Blue RJ45 Gigabit',
                'HDMI Cable 2.0 5m 4K@60Hz Gold Plated',
                'Wireless Access Point Dual Band AC1750',
                'Network Patch Panel 24 Port Cat6 Rackmount',
                'Server Rack Cabinet 42U 800x1000mm Vented Door',
                'UPS 1500VA Line Interactive LCD Display',
                'Surge Protector 6 Outlet 2m Cable 2100J',
                'Laptop Cooling Pad Dual Fan Adjustable Height',
            ]),
            'Packaging' => $this->faker->randomElement([
                'Cardboard Box 600x400x400mm Single Wall',
                'Cardboard Box 300x300x300mm Double Wall Heavy Duty',
                'Archive Box with Lid 406x305x260mm Kraft',
                'Mailing Box 220x160x80mm Postal Die Cut',
                'Stretch Film Roll 20mic 500mm x 300m Clear',
                'Stretch Film Roll 25mic 400mm x 250m Black',
                'Mini Stretch Film 100mm x 150m Hand Wrap',
                'Packing Tape 48mm x 66m Brown Solvent',
                'Packing Tape 50mm x 132m Clear Low Noise',
                'Fragile Tape 48mm x 66m Printed Warning',
                'Bubble Wrap Roll 100m x 500mm Small Bubble',
                'Bubble Wrap Roll 50m x 750mm Large Bubble',
                'Bubble Bags 230x280mm Self Seal (100)',
                'Void Fill Paper Shredded Recyclable 10kg Box',
                'Air Pillows 200x100mm Inflatable Cushions (500)',
                'Foam Corner Protectors 50x50x5mm (100)',
                'Pallet Wrap Dispenser Heavy Duty Metal',
                'Strapping Kit 12mm PET Strap Manual Tensioner',
                'Edge Protectors Cardboard 50x50x1000mm (50)',
                'Cable Ties 300x4.8mm Black UV Resistant (100)',
                'Poly Bags 305x406mm 50mic Clear (1000)',
                'Mailing Bags 320x440mm Grey Self Seal (100)',
                'Jiffy Bags Size 3 195x343mm Gold Padded (100)',
                'Tissue Paper 500x750mm White Acid Free (480)',
                'Shipping Labels 99x139mm Self Adhesive (100)',
            ]),
            'Maintenance' => $this->faker->randomElement([
                'Multi-Purpose Cleaner 5L Concentrate Surface Safe',
                'Multi-Purpose Spray 750ml Antibacterial Trigger',
                'Industrial Degreaser 25L Heavy Duty Alkaline',
                'Degreaser Spray 500ml Fast Acting Aerosol',
                'Floor Cleaning Pads 17" Red Heavy Scrub (5)',
                'Floor Cleaning Pads 20" White Polish (5)',
                'Microfiber Mop Head 40cm Professional Blue',
                'Kentucky Mop Head 450g Cotton Yarn',
                'Hand Soap Dispenser 1L Wall Mount Lockable',
                'Hand Soap Liquid 5L Antibacterial Refill',
                'Paper Towels Roll 2-Ply White 150m (6 rolls)',
                'Center Pull Roll Blue 2-Ply 150m (6 rolls)',
                'Toilet Paper 2-Ply White 320 Sheet (36 rolls)',
                'Jumbo Toilet Roll 2-Ply 300m (6 rolls)',
                'Bin Bags Heavy Duty 90L Black (200)',
                'Refuse Sacks 120L Extra Strong (100)',
                'Yellow Wet Floor Safety Sign Folding',
                'Caution Barrier Tape Roll 75mm x 500m',
                'Broom Soft Bristle 12" with Handle',
                'Squeegee Floor 600mm Rubber Blade Heavy Duty',
                'Bucket 12L Plastic with Mop Wringer',
                'Spray Bottle 750ml Trigger Chemical Resistant',
                'Scrubbing Brush Stiff Bristle Hand Held',
                'Scouring Pads Heavy Duty Green (10)',
                'Cloths All Purpose 40x40cm Blue (10)',
            ]),
            'Safety Equipment' => $this->faker->randomElement([
                'Safety Goggles Clear Anti-Fog EN166',
                'Face Shield Full Face Polycarbonate Visor',
                'Ear Plugs Foam Disposable SNR 37dB (200 pairs)',
                'Ear Defenders Folding SNR 32dB Adjustable',
                'Dust Mask FFP2 Valved Respirator (20)',
                'Respirator Half Face P3 Reusable',
                'Hi-Vis Vest Yellow Class 2 EN ISO 20471',
                'Hi-Vis Jacket Orange Waterproof Fleece Lined',
                'Safety Boots S3 Steel Toe Cap Black Size 9',
                'Safety Trainers S1P Composite Toe Size 8',
                'First Aid Kit Workplace BS 8599-1 Medium',
                'First Aid Kit Portable Travel 20 Person',
                'Eye Wash Station Wall Mount 1L Bottles',
                'Burn Gel Sachets 3.5g Sterile (10)',
                'Disposable Gloves Nitrile Blue Powder Free M (100)',
                'Chemical Gloves Neoprene 330mm Green Size 10',
                'Fire Extinguisher 6kg Powder ABC Class',
                'Fire Extinguisher 2L Foam AFFF Stored Pressure',
                'Fire Blanket 1.2m x 1.2m Kitchen Safety',
                'Smoke Alarm Optical 9V Battery Operated',
                'Safety Harness Full Body Fall Arrest EN361',
                'Lanyard 2m Shock Absorbing Double Leg',
                'Spill Kit Oil Only 25L Portable Bag',
                'Spill Absorbent Granules 20kg Clay Based',
                'Lockout Tagout Kit Electrical 12 Component',
            ]),
            'Furniture & Fixtures' => $this->faker->randomElement([
                'Office Desk 1600x800mm White Rectangular',
                'Height Adjustable Desk Electric 1400x700mm Oak',
                'Corner Desk L-Shape 1800x1400mm Grey',
                'Filing Cabinet 3 Drawer Steel Grey',
                'Mobile Pedestal 3 Drawer with Cushion Top Black',
                'Storage Cabinet 2 Door Steel 1800x900mm',
                'Bookcase 5 Shelf 1800x900x400mm Oak Veneer',
                'Meeting Table 2400x1200mm Boardroom Walnut',
                'Folding Table 1800x750mm Trestle White',
                'Reception Desk 1600mm Curved Front Beech',
                'Office Chair Mid Back Mesh Ergonomic Black',
                'Executive Chair High Back Leather Brown',
                'Conference Chair Stacking Fabric Blue (4)',
                'Visitor Chair Cantilever Frame Chrome Grey',
                'Stool Adjustable Height Gas Lift Black',
                'Coat Stand 8 Hook Metal Weighted Base',
                'Coat Hangers Wooden Trouser Bar (20)',
                'Locker 2 Door Steel 1800x300x450mm Grey',
                'Notice Board Cork 1200x900mm Aluminum Frame',
                'Whiteboard Magnetic 1200x900mm Wall Mount',
                'Flip Chart Easel Adjustable Height Mobile',
                'Shelving Unit 5 Tier Boltless 1800x900x400mm',
                'Pallet Racking Frame 2700x900mm Heavy Duty',
                'Wire Mesh Security Cage 2000x2000x2000mm',
                'Room Divider Screen 3 Panel Fabric Grey',
            ]),
            'Electrical Supplies' => $this->faker->randomElement([
                'LED Bulb A60 9W E27 Warm White 3000K',
                'LED Tube T8 18W 1200mm Cool White 6500K',
                'LED Panel 600x600mm 40W 4000K Recessed',
                'Emergency Light Twin Spot 3W LED 3Hr Battery',
                'Extension Lead 4 Socket 2m Cable Surge Protected',
                'Extension Reel 25m 4 Socket 13A Thermal Cut Out',
                'Timer Switch Digital 7 Day Programmable Socket',
                'Plug Top 13A White Fused BS1363',
                'Socket Outlet Double Switched White Metal Clad',
                'Junction Box 100x100x50mm IP55 Weatherproof',
                'Cable Trunking 50x50mm 3m White PVC',
                'Conduit PVC 25mm Heavy Gauge 3m Black',
                'Twin & Earth Cable 2.5mm² Grey 100m Reel',
                'Armored Cable 4mm² 3 Core SWA 50m',
                'Flex Cable 3 Core 1.5mm² Black 10m',
                'Cable Clips 6mm White Plastic (100)',
                'Insulation Tape PVC 19mm x 33m Black',
                'Heat Shrink Tubing Assorted Sizes Kit 160pcs',
                'Terminal Block 12 Way 30A Dual Row',
                'Wire Connectors Push-in 3 Way (50)',
                'RCD Protection 30mA 40A Double Pole',
                'MCB Circuit Breaker Type B 16A Single Pole',
                'Consumer Unit 10 Way Metal Clad 100A',
                'PIR Motion Sensor IP44 Adjustable 180° White',
                'Dimmer Switch LED Compatible 2 Way 400W',
            ]),
            'Laboratory Supplies' => $this->faker->randomElement([
                'Beaker Borosilicate Glass 250ml Low Form',
                'Beaker Plastic PP 1000ml Graduated',
                'Measuring Cylinder Class B 100ml Glass',
                'Volumetric Flask Class A 500ml Glass',
                'Pipette Pasteur Graduated 3ml Plastic (500)',
                'Micropipette 100-1000µl Variable Single Channel',
                'Pipette Tips Yellow 200µl Universal Fit (1000)',
                'Test Tubes Borosilicate 16x150mm Rim Top (100)',
                'Conical Flask Erlenmeyer 500ml Narrow Neck',
                'Petri Dish Sterile 90mm Polystyrene (500)',
                'Watch Glass 100mm Diameter Borosilicate',
                'Funnel Powder 100mm Dia Short Stem Plastic',
                'Stirring Rod Glass 200mm x 6mm Diameter (10)',
                'Spatula Stainless Steel Double End 200mm',
                'Forceps Straight Tip 150mm Stainless Steel',
                'Thermometer Laboratory -10 to 110°C Glass',
                'pH Paper Universal Range 1-14 (100 strips)',
                'Weighing Boat Disposable 89x89x25mm (500)',
                'Filter Paper Qualitative 110mm Dia (100)',
                'Litmus Paper Blue & Red Combo Pack',
                'Laboratory Coat White Cotton Large',
                'Safety Glasses Clear Lens Side Shield',
                'Glove Box Dispenser Triple Wall Mount',
                'Wash Bottle 500ml LDPE Squeeze Type',
                'Desiccator Vacuum 200mm Clear Polycarbonate',
            ]),
            'Catering & Kitchen' => $this->faker->randomElement([
                'Plates White Porcelain 260mm Dinner (12)',
                'Bowls White Porcelain 150mm Soup (12)',
                'Mugs White Porcelain 300ml Coffee (6)',
                'Cutlery Set Stainless Steel 24 Piece Service 6',
                'Glasses Tumbler 285ml Stackable (6)',
                'Coffee Cups White 200ml with Saucer (6)',
                'Water Jug Glass 1.5L with Handle',
                'Food Storage Container 5L Clear PP with Lid',
                'Cling Film 300mm x 300m Commercial Catering',
                'Aluminum Foil Roll 450mm x 75m Heavy Duty',
                'Kitchen Roll Paper Towel 2-Ply White (12)',
                'Dishwasher Tablets All-in-One (100)',
                'Washing Up Liquid 5L Lemon Professional',
                'Bin Pedal 60L Stainless Steel Kitchen',
                'Bin Liners 60L Clear Pedal Bin (50)',
                'Microwave Oven 900W 25L Digital Stainless',
                'Kettle Electric 3kW 1.7L Stainless Steel',
                'Toaster 4 Slice Commercial Stainless Steel',
                'Coffee Machine Bean to Cup 1450W',
                'Water Boiler 20L Wall Mount Catering',
                'Chopping Board HDPE 450x300x12mm White',
                'Kitchen Knife Set 5 Piece Professional',
                'Mixing Bowl Stainless Steel 5L',
                'Colander Stainless Steel 280mm Diameter',
                'Can Opener Manual Heavy Duty Commercial',
            ]),
            'Printing & Stationery' => $this->faker->randomElement([
                'Printer Paper A4 80gsm Ultra White (2500 sheets)',
                'Printer Paper A3 100gsm Laser 500 Sheets',
                'Photo Paper Glossy A4 180gsm (100 sheets)',
                'Cardstock A4 250gsm White Smooth (250 sheets)',
                'Ink Cartridge Black XL High Yield HP Compatible',
                'Ink Cartridge Tri-Color Standard Canon Compatible',
                'Toner Cartridge Black 3000 Pages Brother Compatible',
                'Laser Toner Cyan 2300 Pages Samsung Compatible',
                'Notepads A4 Ruled 80 Sheets Perforated (10)',
                'Notebooks A5 Hardback 192 Pages Ruled',
                'Spiral Notebook A4 Wirebound 160 Pages',
                'Index Cards A6 Ruled White 100gsm (100)',
                'Business Cards 400gsm Matt Laminated (500)',
                'Compliment Slips DL 100gsm White (1000)',
                'Letterhead A4 100gsm Printed Color (500)',
                'Invoice Books Duplicate NCR A5 (5)',
                'Receipt Books 2-Part NCR 100 Sets',
                'Franking Labels Single 140x38mm (1000)',
                'Address Labels A4 21 Per Sheet (2100)',
                'CD Labels Full Face Glossy (50)',
                'Laminating Pouches A4 150mic Gloss (100)',
                'Binding Combs 21 Ring 16mm Black (100)',
                'Binding Covers A4 Clear PVC 200mic (100)',
                'Report Files Slide Binder A4 Clear (25)',
                'Presentation Folders A4 Gloss Laminated (10)',
            ]),
            'Tools & Equipment' => $this->faker->randomElement([
                'Cordless Drill 18V Li-Ion 2x2.0Ah Batteries',
                'Impact Driver 18V Brushless 180Nm Torque',
                'Angle Grinder 115mm 850W 11000rpm',
                'Circular Saw 185mm 1400W Laser Guide',
                'Jigsaw Variable Speed 600W Orbital Action',
                'Multi-Tool Oscillating 300W Quick Change',
                'Heat Gun 2000W 2 Speed Settings LCD Display',
                'Soldering Iron 60W Temperature Controlled',
                'Tool Box 22" Structural Foam Organizer',
                'Tool Chest 7 Drawer Roller Cabinet Red',
                'Socket Set 1/2" Drive 120 Piece Metric',
                'Spanner Set Combination 8-19mm Chrome (12)',
                'Screwdriver Set 6 Piece Slotted Phillips',
                'Hex Key Set Metric Ball End 9 Piece',
                'Pliers Set 3 Piece Long Nose Side Cutter',
                'Adjustable Wrench 250mm Chrome Vanadium',
                'Pipe Wrench 350mm Capacity 50mm Heavy Duty',
                'Hacksaw Adjustable 300mm Bi-Metal Blade',
                'Spirit Level 600mm Magnetic 3 Vial',
                'Tape Measure 8m x 25mm Metric Imperial',
                'Digital Caliper 150mm Stainless Steel LCD',
                'Micrometer External 0-25mm 0.01mm Resolution',
                'Utility Knife Retractable Auto-Load 18mm',
                'Chisel Set Wood Bevel Edge 6 Piece',
                'Clamp G-Type 150mm Capacity Malleable Iron',
            ]),
            'Automotive Supplies' => $this->faker->randomElement([
                'Engine Oil 5W-30 Fully Synthetic 5L',
                'Engine Oil 10W-40 Semi-Synthetic 20L',
                'Hydraulic Oil ISO 46 20L Mineral',
                'Brake Fluid DOT 4 1L High Performance',
                'Antifreeze Coolant Concentrated 5L Red',
                'Windscreen Washer Fluid 5L All Seasons',
                'Grease Lithium Complex EP2 12.5kg Cartridge',
                'WD-40 Multi-Use 5L Bulk Can',
                'Degreaser Heavy Duty 5L Aerosol Spray',
                'Air Filter Universal Foam 60mm ID',
                'Oil Filter Spin-On M20x1.5 Thread',
                'Fuel Filter Inline 8mm Petrol Diesel',
                'Spark Plugs Standard Copper 14mm (4)',
                'Wiper Blades 22" Universal Hook Fitting',
                'Bulb H7 12V 55W Halogen (2)',
                'Fuses Blade Standard Mixed Pack (100)',
                'Battery 12V 70Ah 640A Calcium Silver',
                'Jump Leads 3m 600A Heavy Duty Clamps',
                'Tyre Inflator Digital 12V Portable Compressor',
                'Tyre Pressure Gauge Digital 0-100 PSI',
                'Jack Trolley 2 Tonne Low Entry Professional',
                'Axle Stands 3 Tonne Pair Ratchet Type',
                'Funnel Flexible Spout 160mm Diameter',
                'Oil Drain Pan 16L Polyethylene Pouring Lip',
                'Mechanic Gloves Synthetic Leather XL',
            ]),
            'Medical Supplies' => $this->faker->randomElement([
                'Disposable Gloves Latex Powdered Medium (100)',
                'Nitrile Gloves Powder-Free Blue Large (100)',
                'Vinyl Gloves Clear Powder-Free Small (100)',
                'Face Masks Type IIR 3-Ply Blue (50)',
                'Surgical Masks FFP2 White Individually Wrapped (20)',
                'Aprons Disposable Polythene White (100)',
                'Alcohol Wipes 70% IPA 75x45mm (200)',
                'Hand Sanitizer Gel 70% Alcohol 500ml Pump',
                'Clinical Waste Bags Yellow 20L (50)',
                'Sharps Container 5L Orange Lid Lockable',
                'Bandages Crepe 75mm x 4.5m Stretched (12)',
                'Cohesive Bandage 50mm x 4.5m Blue (18)',
                'Gauze Swabs Sterile 100mm x 100mm (100)',
                'Adhesive Dressing 72mm x 25mm Fabric (100)',
                'Medical Tape Microporous 25mm x 9m (12)',
                'Plasters Assorted Waterproof (100)',
                'Scissors Stainless Steel 140mm Blunt Tip',
                'Tweezers Straight Tip 115mm Stainless',
                'Thermometer Digital Oral Fast Read',
                'Blood Pressure Monitor Automatic Upper Arm',
                'Tongue Depressors Wooden 150mm (100)',
                'Specimen Containers Sterile 30ml (100)',
                'Syringes 5ml Luer Lock Sterile (100)',
                'Needles Hypodermic 21G x 1.5" Green (100)',
                'Cotton Wool 500g Roll Medical Grade',
            ]),
            'Textiles & Uniforms' => $this->faker->randomElement([
                'Polo Shirt Navy 100% Cotton Embroidered Logo M',
                'T-Shirt Black Heavy Cotton 185gsm Crew Neck L',
                'Work Trousers Navy Multi-Pocket Polycotton 32R',
                'Coveralls Royal Blue Boilersuit Size 42',
                'Hi-Vis Polo Shirt Yellow Orange Piping XL',
                'Fleece Jacket Navy Full Zip Micro-Fleece L',
                'Softshell Jacket Black Waterproof Breathable M',
                'Shirts White Long Sleeve Easy Care 16.5"',
                'Tabard Red Disposable Polypropylene (10)',
                'Chef Jacket White Double Breasted Large',
                'Chef Trousers Black Elasticated Waist XL',
                'Chef Hat White Disposable Paper (100)',
                'Apron Bib Black Cotton Adjustable Neck',
                'Lab Coat White 100% Cotton 3 Pockets M',
                'Scrubs Set Teal V-Neck Top Drawstring Pants M',
                'Towels Bath White 450gsm 100% Cotton (12)',
                'Hand Towels White 400gsm 50x90cm (12)',
                'Tea Towels White 100% Cotton Hemmed (10)',
                'Bed Sheets Single White Polycotton (10)',
                'Duvet Cover Double White Percale 200TC',
                'Pillow Cases White Oxford Style (4)',
                'Blankets Fleece Navy 150x200cm',
                'Curtains Blackout Grey 229x229cm Pencil Pleat',
                'Tablecloths White 137x229cm Polycotton',
                'Napkins White 50x50cm 100% Cotton (12)',
            ]),
            'Gardening & Grounds' => $this->faker->randomElement([
                'Spade Digging Stainless Steel Blade D-Handle',
                'Fork Digging 4 Tine Carbon Steel T-Handle',
                'Rake Garden 16 Teeth Forged Steel Head',
                'Hoe Dutch Push Pull 140mm Blade Long Handle',
                'Trowel Hand Stainless Steel Soft Grip',
                'Pruning Shears Bypass 200mm Teflon Coated',
                'Hedge Shears 540mm Wavy Blade Steel Handles',
                'Lawn Mower Petrol 139cc 16" Self-Propelled',
                'Strimmer Electric 250W 23cm Cutting Width',
                'Leaf Blower Cordless 18V 2.0Ah Battery',
                'Wheelbarrow 85L Galvanized Pneumatic Wheel',
                'Garden Hose 30m Reinforced PVC 12mm',
                'Hose Reel Wall Mount 40m Capacity Auto Rewind',
                'Sprinkler Oscillating Adjustable Width Pattern',
                'Watering Can 10L Galvanized Metal Long Spout',
                'Compost Bin 330L Black Recycled Plastic',
                'Garden Waste Bags 120L Heavy Duty (5)',
                'Weed Killer Glyphosate 5L Concentrate',
                'Lawn Feed Spring Summer 10kg Covers 285m²',
                'Fertilizer General Purpose 20kg NPK',
                'Pest Control Slug Pellets 800g Metaldehyde',
                'Plant Support Canes Bamboo 120cm (20)',
                'Tree Ties Strap 45cm Rubber Cushion (10)',
                'Landscape Fabric 2m x 10m Weed Control',
                'Bark Mulch Decorative 100L Play Grade',
            ]),
            'Security & Surveillance' => $this->faker->randomElement([
                'CCTV Camera Dome 5MP IP PoE IR 30m',
                'CCTV Camera Bullet 4MP HD-TVI IR 40m',
                'NVR 8 Channel 4K H.265 4TB HDD Included',
                'DVR 16 Channel 1080p H.264 2TB HDD',
                'Monitor CCTV 21.5" LED 1920x1080 HDMI VGA',
                'Camera Cable RG59 + Power 100m Black',
                'BNC Connectors Crimp Type Male (50)',
                'Power Supply 12V 5A CCTV Camera 4-Way',
                'Alarm Panel 8 Zone Expandable LCD Keypad',
                'PIR Detector Pet Immune 25kg Dual Tech',
                'Door Contact Magnetic Surface Mount White',
                'Glass Break Detector Acoustic 360° Coverage',
                'Siren Alarm Bell 120dB Weatherproof Red',
                'Strobe Light Blue LED Flashing 12V',
                'Access Control Keypad Standalone 500 Users',
                'Proximity Reader 125kHz EM Wiegand Output',
                'Access Cards RFID 125kHz Thin (10)',
                'Key Fobs RFID 125kHz Black (10)',
                'Electric Strike Lock 12V DC Fail Safe',
                'Magnetic Lock 280kg Holding Force 12V',
                'Door Closer Overhead Adjustable Size 3',
                'Exit Button Push to Exit Green Illuminated',
                'Intercom Video 7" Color Monitor 4-Wire',
                'Panic Button Emergency Red Flush Mount',
                'Cable Alarm 6 Core 100m Screened CCA',
            ]),
            'HVAC & Ventilation' => $this->faker->randomElement([
                'Air Conditioning Unit Split 12000 BTU A++ Inverter',
                'Portable Air Conditioner 9000 BTU Remote Control',
                'Dehumidifier 20L/Day Continuous Drain Timer',
                'Humidifier Ultrasonic 5L Dual Mist Cool Warm',
                'Fan Pedestal 16" Oscillating 3 Speed Remote',
                'Fan Desk 12" Metal Chrome 3 Speed',
                'Extractor Fan 100mm Timer Humidity Sensor',
                'Inline Fan 150mm Mixed Flow 460m³/h',
                'Ducting Flexible Aluminum 150mm x 3m',
                'Ducting Rigid PVC 100mm x 500mm White',
                'Grille Air Vent 300x150mm White Adjustable',
                'Diffuser Ceiling Round 200mm White Plastic',
                'Heater Fan 3kW Industrial Drum 415V',
                'Convector Heater 2kW Panel Wall Mount Thermostat',
                'Oil Filled Radiator 2500W 11 Fin Thermostat',
                'Infrared Heater 2kW Wall Mount Remote Control',
                'Thermostat Room Digital Programmable 7-Day',
                'Thermostat Wireless RF Programmable 5/2 Day',
                'Refrigerant R32 Gas 3kg Cylinder',
                'Vacuum Pump 170L/min Two Stage 1/2HP',
                'Manifold Gauge Set R410a R32 Digital 4-Valve',
                'Thermometer Infrared Non-Contact -50 to 550°C',
                'Pipe Insulation Foam 22mm x 9mm x 2m',
                'Condensate Pump 10L/h 230V Silent Operation',
                'Air Purifier HEPA Filter 300m³/h Ionizer',
            ]),
            'Janitorial Equipment' => $this->faker->randomElement([
                'Floor Scrubber Walk-Behind Battery 45cm Deck',
                'Floor Polisher 450mm 1500W Twin Speed',
                'Wet & Dry Vacuum 80L 3000W Stainless Tank',
                'Carpet Cleaner Upright 500W 4.5L Tank',
                'Steam Cleaner Professional 4 Bar 1.5L Boiler',
                'Pressure Washer Electric 2200W 165 Bar',
                'Cleaning Trolley Janitor Cart 3 Shelf Grey',
                'Mop Bucket Wringer 20L Kentucky Yellow',
                'Mop Bucket Dual 2x15L Red Blue Code',
                'Caution Sign Wet Floor Folding Yellow (3)',
                'Window Cleaning Kit Pole 3.6m Extension',
                'Squeegee Window 450mm Complete Handle',
                'Dustpan & Brush Set Long Handle Blue',
                'Broom Yard Stiff Bass 12 Knot Handle',
                'Brush Deck Scrub Stiff Bristle with Handle',
                'Sponge Scourer Non-Scratch Green (10)',
                'Cloths Microfiber All Purpose 40x40cm (10)',
                'Duster Feather 600mm Natural Ostrich',
                'Gloves Rubber Household Pink Large (12 pairs)',
                'Apron PVC Waterproof Blue Bib Style',
                'Buckets Plastic 12L Red Food Safe (3)',
                'Bottles Spray Trigger 750ml Chemical Resistant (6)',
                'Dispenser Paper Towel Centrefeed Wall Mount',
                'Soap Dispenser Foam 1L Lockable White',
                'Air Freshener Aerosol 400ml Mixed Fragrances (12)',
            ]),
            'Signage & Display' => $this->faker->randomElement([
                'A-Board Pavement Sign Black Chalkboard 600x800mm',
                'Poster Frame A1 Snap Clip Silver Aluminum',
                'Poster Frame A2 Lockable Security Aluminum',
                'Display Board Folding 3 Panel 1800x900mm Grey',
                'Notice Board Cork 1200x900mm Wood Frame',
                'Whiteboard Magnetic 1800x1200mm Aluminum Tray',
                'Blackboard 600x900mm Wooden Frame Wall Mount',
                'Banner Stand Roll Up 850x2000mm Portable',
                'Banner Stand Pop Up 3x2 Curved Graphics',
                'Poster Holder Floor Standing A4 Adjustable Height',
                'Menu Board LED Illuminated A3 Slim Light Box',
                'Sign Holder Acrylic A5 Portrait Slanted',
                'Sign Holder A4 Wall Mount Portrait Clear',
                'Brochure Holder DL 1/3 A4 Counter 3 Tier',
                'Business Card Holder Desktop Clear Acrylic',
                'Shelf Barker Ticket Holder 40mm Clear (50)',
                'Cable Display Kit Wire Hanging 2m Adjustable',
                'Crowd Barrier Post Retractable Belt 3m Red',
                'Queue Barrier Post Rope Red Velvet Chrome',
                'Safety Sign Fire Exit Running Man 300x100mm',
                'Safety Sign No Smoking 200mm Self Adhesive',
                'Safety Sign First Aid Cross 200x200mm Rigid',
                'Directional Sign Arrow Aluminum 450x150mm',
                'Room Number Sign Acrylic 150x150mm Custom',
                'Vinyl Lettering Custom Cut Self Adhesive per m²',
            ]),
            default => $this->faker->words(3, true),
        };

        // Price distribution: many cheaper items, some expensive
        $priceTier = $this->faker->numberBetween(1, 10);
        if ($priceTier <= 6) {
            $price = $this->faker->randomFloat(2, 5, 100); // 60%
        } elseif ($priceTier <= 9) {
            $price = $this->faker->randomFloat(2, 100, 500); // 30%
        } else {
            $price = $this->faker->randomFloat(2, 500, 5000); // 10%
        }

        // Stock distribution skewed towards 10-200
        $stockTier = $this->faker->numberBetween(1, 10);
        if ($stockTier <= 7) {
            $stock = $this->faker->numberBetween(10, 200);
        } elseif ($stockTier <= 9) {
            $stock = $this->faker->numberBetween(200, 1000);
        } else {
            $stock = $this->faker->numberBetween(0, 20);
        }

        return [
            'name' => $baseName,
            'sku' => strtoupper($this->faker->unique()->bothify('PRD-####-????')),
            'price' => $price,
            'stock' => $stock,
            'category_id' => $categoryId,
            'market_id' => Market::factory(),
        ];
    }
}
